///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RegisterModel {
/*
{
  "id": 4,
  "token": "QpwL5tke4Pnpja7X4"
} 
*/

  int? id;
  String? token;

  RegisterModel({
    this.id,
    this.token,
  });
  RegisterModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['token'] = token;
    return data;
  }
}
